addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

install: echo "skip bundle install"

env:
  - CHEF_LICENSE=accept

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=chefdk-debian-9
  - INSTANCE=chefdk-debian-10
  - INSTANCE=chefdk-centos-6
  - INSTANCE=chefdk-centos-7
  - INSTANCE=chefdk-centos-8
  - INSTANCE=chefdk-centos-7 CHEF_VERSION=13
  - INSTANCE=chefdk-centos-7 CHEF_VERSION=14
  - INSTANCE=chefdk-ubuntu-1604
  - INSTANCE=chefdk-ubuntu-1804
  - INSTANCE=chefdk-ubuntu-2004
  - INSTANCE=chefdk-ubuntu-1604 CHEF_VERSION=13
  - INSTANCE=chefdk-ubuntu-1604 CHEF_VERSION=14

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - delivery local all
      env:
        - UNIT_AND_LINT=1
        - CHEF_LICENSE=accept
